src/Entity/Path.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PathRepository")
 */
class Path
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotNull()
     * @ORM\Column(type="text")
     */
    private $path;

    /**
     * @Assert\NotNull()
     * @ORM\Column(type="text")
     */
    private $pathLocation;

    /**
     * @Assert\NotNull(message="Vous êtes obligé de remplir au moins ce champ")
     * @ORM\Column(name="titre", type="string")
     */
    private $titre;

    /**
     * @ORM\Column(name="typeSportMarche", type="boolean", nullable=true)
     */
    private $typeSportMarche;

    /**
     * @ORM\Column(name="typeSportCourse", type="boolean", nullable=true)
     */
    private $typeSportCourse;

    /**
     * @ORM\Column(name="typeSportVelo", type="boolean", nullable=true)
     */
    private $typeSportVelo;

    /**
     * @ORM\Column(name="typeSportVTT", type="boolean", nullable=true)
     */
    private $typeSportVTT;

    /**
     * @ORM\Column(name="typeSportAutre", type="boolean", nullable=true)
     */
    private $typeSportAutre;

    /**
     * @ORM\Column(name="description", type="string", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(name="image", type="string", nullable=true)
     *
     * @Assert\File(mimeTypes={ "image/png", "image/jpeg", "image/jpg" }, mimeTypesMessage="Ce format ( {{type}} ) n'est pas supporté. Merci d'entrer une image au format PNG, JPEG ou JPG", maxSize="5M", maxSizeMessage="Le poids de votre image est trop important ({{ size }} {{ suffix }}). Elle peut avoir un poids de {{ limit }} {{ suffix }} au maximum", disallowEmptyMessage="L'image est vide ??", uploadErrorMessage="Erreur lors du téléchargement de votre image, réessayez")
     */
    private $image;

    /**
     * @ORM\Column(name="autre_filtre", type="json_array", nullable=true)
     */
    private $autre_filtre;

    /**
     * @ORM\Column(name="distance", type="integer", nullable=true)
     */
    private $distance;

    /**
     * @ORM\Column(name="auteur", type="string")
     */
    private $auteur;

    /**
     * @ORM\Column(name="slug", type="string")
     */
    private $slug;






    /**
     * @return mixed
     */
    public function getTitre()
    {
        return $this->titre;
    }

    /**
     * @param mixed $titre
     */
    public function setTitre($titre): void
    {
        $this->titre = $titre;
    }

    /**
     * @return mixed
     */
    public function getTypeSportMarche()
    {
        return $this->typeSportMarche;
    }

    /**
     * @param mixed $typeSportMarche
     */
    public function setTypeSportMarche($typeSportMarche): void
    {
        $this->typeSportMarche = $typeSportMarche;
    }

    /**
     * @return mixed
     */
    public function getTypeSportCourse()
    {
        return $this->typeSportCourse;
    }

    /**
     * @param mixed $typeSportCourse
     */
    public function setTypeSportCourse($typeSportCourse): void
    {
        $this->typeSportCourse = $typeSportCourse;
    }

    /**
     * @return mixed
     */
    public function getTypeSportVelo()
    {
        return $this->typeSportVelo;
    }

    /**
     * @param mixed $typeSportVelo
     */
    public function setTypeSportVelo($typeSportVelo): void
    {
        $this->typeSportVelo = $typeSportVelo;
    }

    /**
     * @return mixed
     */
    public function getTypeSportVTT()
    {
        return $this->typeSportVTT;
    }

    /**
     * @param mixed $typeSportVTT
     */
    public function setTypeSportVTT($typeSportVTT): void
    {
        $this->typeSportVTT = $typeSportVTT;
    }

    /**
     * @return mixed
     */
    public function getTypeSportAutre()
    {
        return $this->typeSportAutre;
    }

    /**
     * @param mixed $typeSportAutre
     */
    public function setTypeSportAutre($typeSportAutre): void
    {
        $this->typeSportAutre = $typeSportAutre;
    }

    /**
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param mixed $description
     */
    public function setDescription($description): void
    {
        $this->description = $description;
    }

    /**
     * @return mixed
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @param mixed $image
     */
    public function setImage($image)
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return mixed
     */

    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * @param mixed $path
     */
    public function setPath($path): void
    {
        $this->path = $path;
    }

    /**
     * @return mixed
     */
    public function getPathLocation()
    {
        return $this->pathLocation;
    }

    /**
     * @param mixed $pathLocation
     */
    public function setPathLocation($pathLocation): void
    {
        $this->pathLocation = $pathLocation;
    }

    /**
     * @return mixed
     */
    public function getAutreFiltre()
    {
        return $this->autre_filtre;
    }

    /**
     * @param mixed $autre_filtre
     */
    public function setAutreFiltre($autre_filtre): void
    {
        $this->autre_filtre = $autre_filtre;
    }

    /**
     * @return mixed
     */
    public function getDistance()
    {
        return $this->distance;
    }

    /**
     * @param mixed $distance
     */
    public function setDistance($distance): void
    {
        $this->distance = $distance;
    }

    /**
     * @return mixed
     */
    public function getAuteur()
    {
        return $this->auteur;
    }

    /**
     * @param mixed $auteur
     */
    public function setAuteur($auteur): void
    {
        $this->auteur = $auteur;
    }

    public function getSlug()
    {
        return $this->slug;
    }

    public function setSlug($text)
    {
        $this->slug = $this->slugify($text);
    }

    public function slugify($text)
    {
        // replace non letter or digits by -
        $text = preg_replace('#[^\\pL\d]+#u', '-', $text);

        // trim
        $text = trim($text, '-');

        // transliterate
        if (function_exists('iconv'))
        {
            $text = iconv('utf-8', 'us-ascii//TRANSLIT', $text);
        }

        // lowercase
        $text = strtolower($text);

        // remove unwanted characters
        $text = preg_replace('#[^-\w]+#', '', $text);

        if (empty($text))
        {
            return 'n-a';
        }

        return $text;
    }

}

templates/content/afficherPath.html.twig
{% extends 'base.html.twig' %}

{% block title %}Afficher{{ parent() }}{% endblock %}

{% block stylesheets %}{{ asset('build/concepteur.css') }}{% endblock %}

{% block body %}
    <div id="loading">
        <img id="loading-image" src="{{ asset('images/loader.gif') }}" alt="Loading..." />
    </div>

    <div id="map" oncontextmenu="return false"></div>

    <div id="textDiv" class="textDivDisplay"></div>
    <div id="petitTextDiv"></div>

    <div id="mapFilter" class="mapFilter"></div>

    <button id="boutonMenuLateral" class="boutonMenuLateralStyle"><img src="{{ asset('images/menu-droite.png') }}" alt="Droite" id="imgBoutonMenuGauche"></button>

    <div id="menuGauche">
        <p id="menuGauche-message">Commencez par tracer votre parcours !</p>

        <div id="menuGauche-interieur">
            <div class="menuGauche-partie">
                <p class="menuGauche-partie-texte">Vitesse Moyenne</p>
            </div>

            <div class="menuGauche-partie">
                <div class="sepa-container"><div class="menuGauche-sepa"></div></div>
                <p class="menuGauche-partie-texte">Temps nécessaire</p>
            </div>

            <div class="menuGauche-partie">
                <div class="sepa-container"><div class="menuGauche-sepa"></div></div>
                <div class="menuGauche-partie-container">
                    <img src="{{ asset('images/velo.png') }}" alt="Icône vélo" class="menuGauche-img">
                    <p class="menuGauche-partie-temps-sport"><span title="Avec une vitesse moyenne de 20 km/h">En vélo,</span> vous prendrez <span id="tempsVelo"></span></p>
                </div>
            </div>

            <div class="menuGauche-partie">
                <div class="sepa-container"><div class="menuGauche-sepa"></div></div>
                <div class="menuGauche-partie-container">
                    <img src="{{ asset('images/footing.png') }}" alt="Icône footing" class="menuGauche-img">
                    <p class="menuGauche-partie-temps-sport"><span title="Avec une vitesse moyenne de 13 km/h">Avec une allure de footing,</span> vous prendrez <span id="tempsFooting"></span></p>
                </div>
            </div>

            <div class="menuGauche-partie">
                <div class="sepa-container"><div class="menuGauche-sepa"></div></div>
                <div class="menuGauche-partie-container">
                    <img src="{{ asset('images/marche.png') }}" alt="Icône marche" class="menuGauche-img">
                    <p class="menuGauche-partie-temps-sport"><span title="Avec une vitesse moyenne de 6 km/h">En marchant,</span> vous prendrez <span id="tempsMarche"></span></p>
                </div>
            </div>
        </div>

        <!--<button id="boutonMenuLateralFermer" class="boutonMenuLateralStyle"><img src="img/menu-gauche.png" alt="Gauche"></button>-->
    </div>
    <table>
        <thead>
        <tr>
            <th>Titre</th>
            <th>Type de sport</th>
            <th>Description</th>
            <th>Image</th>
            <th>Note</th>
            <th>Autre filtre</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ path.titre }}</td>
            <td>{{ path.typeSport }}</td>
            <td>{{ path.description }}</td>
            <td>{{ path.image }}</td>
            <td>{{ path.note }}</td>
            <td>{{ path.autreFiltre }}</td>
        </tr>
        </tbody>
    </table>
{% endblock %}

{% block javascripts %}
    {#<script src=" {{ asset('build/js/main.js') }} "></script>#}
    <script src=" {{ asset('build/mousetrap.js') }} "></script>
    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
    <script language="javascript" type="text/javascript">
        $(window).load(function() {
            $('#loading').hide();
        });
    </script>

    <script>
        var globalPoly;

        var map;
        var geoPos;

        var markerStart = "{{ asset('images/marker.png') }}";   //icone de marqueur de début
        var markerEnd = "{{ asset('images/empty.png') }}";

        var vitesseVelo = 20;
        var vitesseFooting = 13;
        var vitesseMarche = 6;




        function initMap() {
            var mapDiv = document.getElementById("map");
            //je récupére mon element avec l'id map
            var windowHeight = window.innerHeight;
            //je prend la hauteur de la fenêtre
            var tailleVoulu = (windowHeight - 80) + 'px';
            //je calcule pour que ma map fasse hauteur de la fenêtre moins le header
            mapDiv.style.height = tailleVoulu;
            //c'est comme si je fais en CSS: 'height: tailleVoulu;'

            //definir taille du menu gauche
            var menuGauche = document.getElementById('menuGauche');
            menuGauche.style.height = tailleVoulu;

            //on veut centrer la carte sur notre position si la geolocalisation est activée
            /*if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function(position){   //recupère notre position
                    geoPos = {
                        lat: position.coords.latitude,
                        lng: position.coords.longitude
                    };

                    map.setCenter(geoPos);   //centre la carte

                }, function() {
                    handleLocationError(true, infoWindow, map.getCenter());
                });

            } else {
                // Le navigateur ne supporte pas la géolocalisation ou elle a été refusé
                handleLocationError(false, infoWindow, map.getCenter());
            };*/


            var ancienPath ='{{ path.path }}';

            var ancienPathDesencode = new google.maps.geometry.encoding.decodePath(ancienPath);

            map = new google.maps.Map(document.getElementById('map'), {    //recupére la div #map et la transforme en objet map, stocké dans la var map
                zoom: 14  //Définie le zoom par défaut
            });

            globalPoly = new google.maps.Polyline({   //créé déjà la polyline
                path: ancienPathDesencode,
                strokeColor: '#3BA14C',
                strokeOpacity: 1.0,
                strokeWeight: 3
            });
            globalPoly.setMap(map);   //on attache l'objet polyline à notre map

            var premierMarker = ancienPathDesencode[0];
            firstMarker = new google.maps.Marker({
                position: premierMarker,
                title: 'Premier marqueur',
                map: map,
                icon: markerStart
            });

            var dernierMarker = ancienPathDesencode[ancienPathDesencode.length - 1];
            marker = new google.maps.Marker({
                position: dernierMarker,
                title: 'Dernier marqueur',
                map: map,
                icon: markerEnd
            });

            google.maps.event.addListener( map, 'maptypeid_changed', function(){
                var mapType = map.getMapTypeId();

                if (mapType == 'hybrid'){
                    globalPoly.setOptions({strokeColor: '#FFFFFF'});
                    firstMarker.setOptions({icon: "{{ asset('images/marker_white.png') }}"});
                } else {
                    globalPoly.setOptions({strokeColor: '#3BA14C'});
                    firstMarker.setOptions({icon: "{{ asset('images/marker.png') }}"});
                }
            });

            var boutonMenuLateral = document.getElementById('boutonMenuLateral');
            map.controls[google.maps.ControlPosition.LEFT].push(boutonMenuLateral);

            updateRouteLength();

            var monPath = globalPoly.getPath();

            var pathArray = monPath.getArray();

            zoomToObject(pathArray);
        }
        /************* FIN INITMAP *************/




        function zoomToObject(pathArray){
            var bounds = new google.maps.LatLngBounds();
            var points = pathArray;
            for (var n = 0; n < points.length ; n++){
                bounds.extend(points[n]);
            }
            map.fitBounds(bounds);
        }

        function updateRouteLength(){
            var monPath = globalPoly.getPath();

            var pathArray = monPath.getArray();

            var distance = google.maps.geometry.spherical.computeLength(pathArray);   //calcule la distance du parcours en comptant tout les points
            distanceArrondie = Math.round(distance);    //arrondi la distance à l'unité près
            distanceKmFloat = distanceArrondie/1000;
            distanceKm = Math.round(distanceKmFloat*10)/10;


            var div = document.getElementById("textDiv");    //recupere la div textDiv
            var petiteDiv = document.getElementById("petitTextDiv");
            if ((distanceArrondie == undefined) || (distanceArrondie == 0)){   //si aucun parcours n'est présent ou s'il n'y a qu'un marqueur
                div.textContent = "Il n'y a qu'un seul marqueur";
            } else {
                div.textContent = distanceKm + " kilomètres" ;
                //on affiche la distance arrondie et au km dans la div textDiv
                petiteDiv.textContent = distanceArrondie + " mètres"

                var menuGaucheInterieur = document.getElementById("menuGauche-interieur");
                menuGaucheInterieur.style.display = "block";

                var menuGaucheMessage = document.getElementById("menuGauche-message");
                menuGaucheMessage.style.display = "none";
            }

            updateTempsGlobal(distanceKmFloat);
        }

        function getDecimal(n) {
            return (n - Math.floor(n));
        }

        function getPartieDecimale(n){
            return (Math.round((Math.round(100 * getDecimal(n))/100) * 100 * 60 / 100));
        }

        function updateTempsGlobal(distanceKmFloat){
            //velo
            updateTempsNecessaire(distanceKmFloat, vitesseVelo, "tempsVelo");

            //footing
            updateTempsNecessaire(distanceKmFloat, vitesseFooting, "tempsFooting");

            //marche
            updateTempsNecessaire(distanceKmFloat, vitesseMarche, "tempsMarche");
        }

        function updateTempsNecessaire(distanceKmFloat, vitesseMoyenne, sport){
            var tempsHTML = document.getElementById(sport); //on récup l'élément p tempsVelo

            var temps = distanceKmFloat / vitesseMoyenne; // t = d / v      on sort le temps qu'il faut en heures (mais on a 1.5 heures au lieu de 1h30)
            var tempsEnMinutesAvecSecondes = Math.round(100 * (temps * 60))/100;  //on sort 52.31 (52 minutes 31 secondes)
            var secondesTemps = getPartieDecimale(tempsEnMinutesAvecSecondes);

            var tempsEnMinutes = Math.round(tempsEnMinutesAvecSecondes);   //on sort juste 52

            if(tempsEnMinutes === 1){
                var minuteOrthographe = " minute";
            }else{
                var minuteOrthographe = " minutes";
            }

            if(secondesTemps === 1){
                var secondeOrthographe = " seconde";
            }else{
                var secondeOrthographe = " secondes";
            }


            if(tempsEnMinutes < 1){
                tempsHTML.textContent = secondesTemps + secondeOrthographe;
                tempsHTML.title = "";
            }else{
                //si il y a plus de 60 minutes on affiche en heures et minutes
                if(tempsEnMinutes < 60){
                    tempsHTML.textContent = tempsEnMinutes + minuteOrthographe;
                    tempsHTML.title = "Et " + secondesTemps + secondeOrthographe;
                }else{
                    var tempsEnHeuresFloat = tempsEnMinutes / 60;
                    var minutesDuTempsPourHeures = getPartieDecimale(tempsEnHeuresFloat); //on recup les minutes
                    var tempsEnHeures = Math.round(tempsEnHeuresFloat);

                    if(minutesDuTempsPourHeures === 1){
                        var minuteOrthographe = " minute";
                    }else{
                        var minuteOrthographe = " minutes";
                    }

                    if(tempsEnHeures === 1){
                        var heureOrthographe = " heure";
                    }else{
                        var heureOrthographe = " heures";
                    }

                    tempsHTML.textContent = tempsEnHeures + heureOrthographe + " et " + minutesDuTempsPourHeures + minuteOrthographe;  //on affiche
                }
            }

        }

        var menuGaucheBouton = document.getElementById('boutonMenuLateral');
        var menuGauche = document.getElementById('menuGauche');
        var mapFilter = document.getElementById('mapFilter');

        menuGaucheBouton.onclick = function() {
            menuGauche.style.display = "block";
            mapFilter.style.display = "block";
        };

        mapFilter.onclick = function() {
            menuGauche.style.display = "none";
            mapFilter.style.display = "none";
        };


        /***** RACCOURCIS CLAVIER ********/
        Mousetrap.bind(['ctrl+z'], function() {
            deleteLastPoint();
        });




        //zoom/dezoom avec Ctrl Alt +/- ou Ctrl +/-
        var zoom = 14;

        Mousetrap.bind(['ctrl+alt++', 'ctrl++'], function() {
            if(zoom <= 23){
                zoom++;
                map.setZoom(zoom);
            }else{
                alert('Impossible de zoomer davantage');
            }
        });

        Mousetrap.bind(['ctrl+alt+-', 'ctrl+-'], function() {
            if(zoom >= 1){
                zoom--;
                map.setZoom(zoom);
            }else{
                alert('Impossible de dézoomer davantage');
            }
        });
    </script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBxvWmkG3pYY6DaFxUzvRiyvttqYjdX15Q&libraries=geometry&callback=initMap">
    </script>
{% endblock %}

templates/content/aide.html.twig
{% extends 'base.html.twig' %}

{% block title %}Aide{{ parent() }}{% endblock %}

{% block stylesheets %}{{ asset('build/aide.css') }}{% endblock %}

{% block body %}
    <div class="margin-left">
        <h1 class="titre">Novice ? Un problème ?</h1>
        <div class="titre-separation"></div>

        <h2 class="sous-titre sous-titre1">Découvrez nos tutoriels</h2>
            <div class="tutoecrit-groupcontainer">
                <div class="tutoecrit-container">
                    <a class="tutoecrit-a" href="http://bit.ly/2MRPnzP">Tracer son premier itinéraire</a>
                    <div class="tutoecrit-sepa"></div>
                </div>

                <div class="tutoecrit-container">
                    <a class="tutoecrit-a" href="#">Partager son itinéraire</a>
                    <div class="tutoecrit-sepa"></div>
                </div>

                <div class="tutoecrit-container">
                    <a class="tutoecrit-a" href="#">Trouver un itinéraire</a>
                    <div class="tutoecrit-sepa"></div>
                </div>
            </div>


        <h2 class="sous-titre sous-titre4">Vous n’avez pas trouvé de solution ?</h2>
            <p class="fin">Décrivez nous votre problème en nous envoyant un message depuis la page <a href="{{ path('contact') }}" class="fin-contact">Contact</a>, nous saurons peut-être vous répondre</p>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}

templates/content/chercher.html.twig
{% extends 'base.html.twig' %}

{% block metakeywords %}
    itinéraire running,
    itinéraire vtt,
    parcours running,
    trajet vélo,
    trouver itinéraires randonnée,
    itinéraire course à pied,
    itinéraire marche à pied,
    parcours randonnée,
    trouver itinéraires vélo,
    trouver itinéraires rando,
    itinéraire randonnée,
    itinéraire sportif,
    parcours rando,
    trouver itinéraires vtt,
    itinéraires sport,
    itinéraire vélo,
    parcours vélo,
    parcours footing,
    trouver itinéraires course à pied,
    itinéraires sportifs,
    itinéraire rando,
    parcours vtt,
    parcours course à pied,
    trouver itinéraires marche,
    trouver un itinéraire
{% endblock %}
{% block metadescription %}Avec itin'R, trouvez l'itinéraire parfait pour votre sortie en vélo, VTT, course à pied, ou encore pour votre randonnée.{% endblock %}
{% block title %}Chercher{{ parent() }}{% endblock %}

{% block stylesheets %}{{ asset('build/chercher.css') }}{% endblock %}
{% block stylesheets2 %}{{ asset('build/form_theme.css') }}{% endblock %}

{% form_theme form 'form/fields.html.twig' %}

{% block body %}
    {% include 'flash_messages.html.twig' %}
    <div class="ref">
        <h2>Trouver un itinéraire de vélo, de VTT, de course à pied ou une randonnée</h2>
        <p>itin'R vous permet de <strong>trouver une randonnée</strong>, un <strong>itinéraire de vélo</strong>, de <strong>VTT</strong>, ou encore de <strong>course à pied</strong></p>
    </div>

    <h1 class="titre margin-left">Vous prévoyez une séance de course à pied, une sortie vélo, une randonnée ou autre ? Trouvez l’itinéraire qu’il vous faut grâçe à Itin'r.</h1>
    <p class="sous-titre margin-left">Nouvelle, nouveau ? <a href="{{ path('aide') }}" class="sous-titre-aide">Découvrez nos tutoriaux </a>ou lisez <a href="{{ path('aide') }}" class="sous-titre-tuto">Comment trouver un itinéraire</a></p>

    <div class="titre-separation margin-left"></div>

    <div class="form-container">
        {{ form_start(form) }}
        <div class="lieu-input-container">
            {{ form_row(form.lieu) }}
            <button id="lieu_gps_btn" name="chercher[gps]" type="button" onclick="fillInAdressGeolocation()"><img src="{{ asset('images/chercher_gps.png') }}" alt="Icône gps" class="lieu-gps-btn-img"/></button>
        </div>
        <div class="form-part1-container">
            <h2 class="titre-form-part">Affinez votre recherche</h2>
            <div class="titre-form-part-separation"></div>

            <h3 class="sous-titre-form-part1">Quel type d’itinéraire cherchez-vous ?</h3>
            <div class="form-part1-typeSportContainer">
                {{ form_row(form.typeSportMarche) }}
                {{ form_row(form.typeSportCourse) }}
                {{ form_row(form.typeSportVelo) }}
                {{ form_row(form.typeSportVTT) }}
                {{ form_row(form.typeSportAutre) }}
            </div>
        </div>

        <div class="form-part2-container">
            <h2 class="titre-form-part">Ou recherchez un parcours précis</h2>
            <div class="titre-form-part-separation"></div>
            {{ form_row(form.recherchePrecise) }}
        </div>
        <div class="submit-container"><button type="submit" id="submit" class="submit-input">Rechercher</button></div>
        {{ form_end(form) }}

    </div>
{% endblock %}

{% block javascripts %}
    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBxvWmkG3pYY6DaFxUzvRiyvttqYjdX15Q&libraries=places&callback=initAutocomplete" async defer></script>
    <script>
        var placeSearch, autocomplete, geocoder;

        //Autocompletion de l'adresse
        function initAutocomplete() {
            geocoder = new google.maps.Geocoder();
            var options = {
                types: ['(regions)'],
                componentRestrictions: {country: ["fr", "be"]}
            };
            autocomplete = new google.maps.places.Autocomplete(
                (document.getElementById('chercher_lieu')),
                options);
        }

        //Rempli la searchbox de notre localisation lorsqu'on appuye sur le bouton géolocalisation
        function fillInAdressGeolocation(){
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function(position){   //recupère notre position
                    geoPos = {
                        lat: position.coords.latitude,
                        lng: position.coords.longitude
                    };

                    geocoder.geocode({
                            'location': geoPos
                        }, function(results, status) {
                        if (status === google.maps.GeocoderStatus.OK) {
                            if (results[1]) {
                                var geoLocationResult = results[2].formatted_address;
                                document.getElementById('chercher_lieu').value = geoLocationResult.substr(6);
                            } else {
                                alert('Aucun résultat trouvé');
                            }
                        } else {
                            alert('Le Geocoder a echoué. Raison: ' + status);
                        }
                    });

                }, function() {
                    handleLocationError(true, infoWindow, map.getCenter());
                });

            } else {
                // Le navigateur ne supporte pas la géolocalisation ou elle a été refusé
                handleLocationError(false, infoWindow, map.getCenter());
            }
        }
    </script>
{% endblock %}

templates/content/chercher_utilisateur.html.twig
{% extends 'base.html.twig' %}

{% block title %}Chercher un utilisateur{{ parent() }}{% endblock %}

{% block stylesheets %}{{ asset('build/chercher_utilisateur.css') }}{% endblock %}

{% block body %}
    {% include 'flash_messages.html.twig' %}

    <h1 class="titre margin-left">Trouver un utilisateur</h1>
    <div class="titre-separation margin-left"></div>

    <div class="form-container">
        {{ form_start(form) }}
        {{ form_row(form.username) }}
        <button type="submit" ><img src="{{ asset('images/chercher_utilisateur.png') }}" alt="Chercher">Chercher</button>
        {{ form_end(form) }}
    </div>
{% endblock %}